/*borschik:include:../../libs/bem-core/common.blocks/i-bem/i-bem.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/i-bem/__internal/i-bem__internal.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/inherit/inherit.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/identify/identify.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/next-tick/next-tick.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/objects/objects.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/functions/functions.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/events/events.vanilla.js*/
/*borschik:include:../../libs/bem-core/common.blocks/i-bem/__dom/i-bem__dom.js*/
/*borschik:include:../../libs/bem-core/common.blocks/jquery/jquery.js*/
/*borschik:include:../../libs/bem-core/common.blocks/loader/_type/loader_type_js.js*/
/*borschik:include:../../libs/bem-core/common.blocks/jquery/__config/jquery__config.js*/
/*borschik:include:../../libs/bem-core/common.blocks/dom/dom.js*/
/*borschik:include:../../libs/bem-core/common.blocks/i-bem/__dom/_init/i-bem__dom_init.js*/
/*borschik:include:../../common.blocks/environment-checker/environment-checker.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/mocha/mocha.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/chai/chai.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/sinon/sinon.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/sinon-chai/sinon-chai.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/simulate-dom-event/simulate-dom-event.js*/
/*borschik:include:../../libs/bem-pr/spec.blocks/spec/spec.js*/